### ISSUE TITLE
CardStack stays on Top of Screen after Naviagtor.push()

### ISSUE THREAD

**Issue by DanielEberl** [matthew-carroll/flutter_ui_challenge_tinder_matching#5]
inside 
**_buildProfileSynopsis()** 
i have modified the 
**Container** 
to be wrapped by an 
**GestureDetector**

```
  Widget _buildProfileSynopsis() {
    return Positioned(
      child: GestureDetector(
        child: Container(
          ),
          padding: const EdgeInsets.all(24.0),
          child: Row(),
        onTap: openDetails,
      )
    );
  }
```

So when I tap the bottom of the card, it navigates to a detail/profile page.

```
  openDetails(){
    print('Tapped');
    widget.onNavigator();
    Navigator.of(context).push(MaterialPageRoute(builder: (context) => NewPage()));
  }
```
The Navigation works fine, but somehow the AnchoredOverlay is recreated after navigating.

It disapears for a second and then comes back on top of the screen.

This is the output of my log:
```

I/flutter (25791): Tapped
I/flutter (25791): Page Build
I/flutter (25791): Desired slide direction null
```

I know, since Navigator.push() is async and setState() is called when I tap the card, it recreates the anchored overlay. Is there a way to dispose the widget before manually?

And thank you for your awesome tutorials!

**Comment by DanielEberl** [comment]
So it turns out, didUpdateWidget() gets called when the navigator pushes the next page, so the widget gets rebuilt. 

I have tried injecting a bool from CardStack  into the DraggableCard to show/hide the overlay, but this approach gets very messy and doesnt work correctly when popping the navigator stack.

I'm thinking of rebuilding the card stack as a stateless widget and working with streambuilders, but currently I don't have the time to do so.

Any suggestions on this issue?

**Comment by DanielEberl** [comment]
So I figured it out. Gotta learn the framework.

Navigator.push() actually creates the page (which is a **widget**) as an **overlay** itself.

Since the AnchoredOverlay resides on top of everything, the cards are still visible when using navigator push.

So my workaround is now to call pushReplacement() on the navigator when navigating through pages.

If you have different pages you navigate from to your detail page, just pass a field like parentPageTag and you can call pushReplacement() again when navigating back.

Actually, FlutterInspector got me to this solution, so I can recommend using this awesome tool to everyone :) 🔢

**Comment by EmperorTigris** [comment]
> So I figured it out. Gotta learn the framework.
> 
> Navigator.push() actually creates the page (which is a **widget**) as an **overlay** itself.
> 
> Since the AnchoredOverlay resides on top of everything, the cards are still visible when using navigator push.
> 
> So my workaround is now to call pushReplacement() on the navigator when navigating through pages.
> 
> If you have different pages you navigate from to your detail page, just pass a field like parentPageTag and you can call pushReplacement() again when navigating back.
> 
> Actually, FlutterInspector got me to this solution, so I can recommend using this awesome tool to everyone :) 🔢

Hey, I have another issue.

When I do Navigator.push() to another page, and go back on the page, the DraggableCard is at the bottom and then slides back to the right position which really looks unpleasant.

**Comment by rajilesh** [comment]
I have added an extra variable for showOverlay to control overlay according to the current page and it worked.
